# Generated by Django 4.2.4 on 2023-08-06 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('auth0user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authz.auth0user', verbose_name='Auth0User')),
            ],
        ),
        migrations.CreateModel(
            name='UsernameSignUpSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('signup_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signup_sessions.signupsession', verbose_name='SignUp Session')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordSignUpSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=150, verbose_name='Password')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('signup_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signup_sessions.signupsession', verbose_name='SignUp Session')),
            ],
        ),
        migrations.CreateModel(
            name='EmailSignUpSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=320, unique=True, verbose_name='Email')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('signup_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signup_sessions.signupsession', verbose_name='SignUp Session')),
            ],
        ),
    ]
