# Generated by Django 4.2.4 on 2023-08-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_account_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('display_name', models.CharField(blank=True, max_length=20, verbose_name='Display Name')),
                ('verified_profile', models.BooleanField(default=False, verbose_name='Verified Profile')),
                ('profile_picture', models.ImageField(blank=True, upload_to='social_profile/profile_pictures/', verbose_name='Profile Picture')),
                ('biography_text', models.TextField(blank='true', max_length=140, verbose_name='Biography Text')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('profile_type', models.CharField(choices=[('Personal', 'Personal'), ('Brand', 'Brand'), ('Organization', 'Organization'), ('Provider', 'Provider')], max_length=20, verbose_name='Social Profile Type')),
                ('private_profile', models.BooleanField(default=False, verbose_name='Private Account')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='SP Account Owner')),
                ('blocked_user', models.ManyToManyField(blank=True, related_name='user_blocked', to='social_profiles.socialprofile')),
                ('followers', models.ManyToManyField(blank=True, related_name='user_followers', to='social_profiles.socialprofile')),
                ('following', models.ManyToManyField(blank=True, related_name='user_following', to='social_profiles.socialprofile')),
                ('pending_request', models.ManyToManyField(blank=True, related_name='pandingRequest', to='social_profiles.socialprofile')),
            ],
        ),
    ]
